services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: link
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d link -U user" ]
      interval: 5s
      timeout: 3s
      retries: 3
