"""change columns

Revision ID: 2d14878891be
Revises: 2e54b250930b
Create Date: 2025-05-08 00:26:00.161559

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2d14878891be"
down_revision: Union[str, None] = "2e54b250930b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_link_associations", "last_seen_update_time")
    op.add_column(
        "chats", sa.Column("tg_chat_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint("chats_chat_id_key", "chats", type_="unique")
    op.create_unique_constraint(None, "chats", ["tg_chat_id"])
    op.drop_column("chats", "chat_id")
    op.drop_column("links", "type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "links",
        sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "chats",
        sa.Column(
            "chat_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(None, "chats", type_="unique")
    op.create_unique_constraint("chats_chat_id_key", "chats", ["chat_id"])
    op.drop_column("chats", "tg_chat_id")
    op.add_column(
        "chat_link_associations",
        sa.Column(
            "last_seen_update_time",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
