"""change columns

Revision ID: 9e5335ea296e
Revises: 2d14878891be
Create Date: 2025-05-08 00:38:23.808003

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e5335ea296e"
down_revision: Union[str, None] = "2d14878891be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "_link_chat_uc", "chat_link_associations", ["link_id", "chat_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "_link_chat_uc", "chat_link_associations", type_="unique"
    )
    # ### end Alembic commands ###
