import pytz

PERIOD_OF_CHECK_SECONDS = 60 * 60
TITLE_MAX_LEN = 100
BODY_MAX_LEN = 200
BATCH_SIZE = 2
PREFIX_API = "/api/v2"
TIMEZONE = pytz.timezone("Europe/Moscow")
LEN_OF_PARTS_GITHUB_URL = 2
MIN_LEN_PATH_PARTS = 3
MIN_LEN_PATH_PARTS_STACKOVERFLOW = 2
