import pytz

SUCCESS_RESPONSE_CODE = 200
UNOTHORIZED_RESPONSE_CODE = 401
SERVER_ERROR_RESPONSE_CODE = 500
VALIDATION_ERROR_RESPONSE_CODE = 422


MIN_LEN_PATH_PARTS = 2
LEN_OF_PARTS_GITHUB_URL = 2
TIMEZONE = pytz.timezone("Europe/Moscow")
