from enum import Enum

import pytz


class ResponseCode(Enum):
    SUCCESS = 200
    UNAUTHORIZED = 401
    SERVER_ERROR = 500
    VALIDATION_ERROR = 422
    NOT_FOUND = 404
    ALREADY_REPORTED = 208


HOST_API_SERVER = "0.0.0.0"
PORT_API_SERVER = 7777
PREFIX_API_SERVER = "/api/v1"
URL_API_SERVER = "http://" + HOST_API_SERVER + ":" + str(PORT_API_SERVER) + PREFIX_API_SERVER
MIN_LEN_PATH_PARTS = 2
LEN_OF_PARTS_GITHUB_URL = 2
TIMEZONE = pytz.timezone("Europe/Moscow")
