"""Add many to many

Revision ID: d08319578b3d
Revises: 49fba33c67e4
Create Date: 2025-05-07 22:42:11.626621

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d08319578b3d"
down_revision: Union[str, None] = "49fba33c67e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_link_associations",
        sa.Column("link_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("filters", sa.JSON(), nullable=True),
        sa.Column(
            "last_seen_update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chats.id"],
        ),
        sa.ForeignKeyConstraint(
            ["link_id"],
            ["links.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("links", sa.Column("type", sa.String(), nullable=True))
    op.add_column("links", sa.Column("count_chats", sa.Integer(), nullable=False))
    op.add_column(
        "links",
        sa.Column(
            "last_update",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.drop_column("links", "chat_id")
    op.drop_column("links", "filters")
    op.drop_column("links", "tags")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "links",
        sa.Column(
            "tags",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "links",
        sa.Column(
            "filters",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "links",
        sa.Column("chat_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column("links", "last_update")
    op.drop_column("links", "count_chats")
    op.drop_column("links", "type")
    op.drop_table("chat_link_associations")
    # ### end Alembic commands ###
