# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Set up environment variables
      run: |
        export PYTHONPATH=$PYTHONPATH:$GITHUB_WORKSPACE
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        make install
    - name: Lint
      run: |
        make lint
    - name: Test with pytest
      env:
        BOT_API_ID: 123456
        BOT_API_HASH: test
        BOT_TOKEN: test
        API_HOST_SERVER: "0.0.0.0"
        API_PORT_SERVER: 7777


        SCRAPPER_GITHUB_TOKEN: test
        SCRAPPER_BATCH_SIZE: 2
        SCRAPPER_BODY_MAX_LEN: 200
        SCRAPPER_TITLE_MAX_LEN: 100

        DB_URL: postgresql+asyncpg://test:password_test@localhost:5432/link
        DB_ECHO: 0

      run: |
        make test
